apiVersion: apps/v1
kind: Deployment
metadata:
  name: rplace-backend
  namespace: rplace
  labels:
    app: backend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: harbor.k8s.inpt.fr/rplace/backend:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: MARIADB_HOST
          value: {{ .Values.backend.MARIADB_HOST }}
        - name: MARIADB_PORT
          value: {{ .Values.backend.MARIADB_PORT }}
        - name: MARIADB_USER
          value: {{ .Values.backend.MARIADB_USER }}
        - name: MARIADB_PASSWORD
          value: {{ .Values.backend.MARIADB_PASSWORD }}
        - name: MARIADB_DATABASE
          value: {{ .Values.backend.MARIADB_DATABASE }}
        - name: MARIADB_DEV
          value: {{ .Values.backend.MARIADB_DEV }}
        - name: REDIS_HOST
          value: {{ .Values.backend.REDIS_HOST }}
        - name: AT_SECRET
          value: {{ .Values.backend.AT_SECRET }}
        - name: RT_SECRET
          value: {{ .Values.backend.RT_SECRET }}
        - name: ROLE_ADMIN
          value: {{ .Values.backend.ROLE_ADMIN }}
        - name: LOCAL_PSCOPE
          value: {{ .Values.backend.LOCAL_PSCOPE }}
      imagePullSecrets:
      - name: rplace-pull-secret
