apiVersion: apps/v1
kind: Deployment
metadata:
  name: rplace-frontend
  namespace: rplace
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: harbor.k8s.inpt.fr/rplace/frontend:v1.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: VITE_APP_BACKEND_URL
          value: "{{ .Values.frontend.VITE_APP_BACKEND_URL }}"
        - name: VITE_APP_BACKEND_API_URL
          value: "{{ .Values.frontend.VITE_APP_BACKEND_API_URL }}"
      imagePullSecrets:
      - name: rplace-pull-secret
