apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-rplace
  namespace: rplace
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns
spec:
  rules:
  - host: rplace.k8s.inpt.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rplace-frontend
            port:
              number: 8080
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: rplace-backend
            port:
              number: 8080
      - path: /socket.io/
        pathType: Prefix
        backend:
          service:
            name: rplace-backend
            port:
              number: 8080
  tls:
  - hosts:
      - rplace.k8s.inpt.fr
    secretName: rplace-tls