apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-frontend
  namespace: rplace
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: rplace.inpt.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rplace-frontend
            port:
              number: 8080