apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-configmap
  namespace: rplace
data:
  mariadb.cnf: |
    [mariadb]
    log-bin                         # enable binary loging
    #plugin_load_add=simple_password_check
    #plugin_load_add=password_reuse_check       # this is alpha maturity
    #plugin_maturity=alpha
    #simple_password_check_minimal_length=5     # default 8
    #simple_password_check_digits=0             # default 1
    #simple_password_check_letters_same_case=0  # default 1
    #simple_password_check_other_characters=0   # default 1
    #strict_password_validation=1              # if set to 1 hash passwords are used
  init.sh: |
    set -ex
    # Generate mysql server-id from pod ordinal index.
    echo "Hi from script"
    [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
    ordinal=${BASH_REMATCH[1]}
    echo [mariadb] > /etc/mysql/conf.d/server-id.cnf
    # Add an offset to avoid reserved server-id=0 value.
    echo server-id=$((100 + $ordinal)) >> etc/mysql/server-id.cnf
  mariadb.sh: |
    [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
    ordinal=${BASH_REMATCH[1]}
    mysql -u root --password=${MARIADB_ROOT_PASSWORD} -e "CREATE USER '${MARIADB_REPL_USER}${ordinal}'@'%' IDENTIFIED BY '${MARIADB_REPL_PASSWORD}';";
    mysql -u root --password=${MARIADB_ROOT_PASSWORD} -e "GRANT REPLICATION SLAVE ON *.* TO '${MARIADB_REPL_USER}${ordinal}'@'%';";
    mysql -u root --password=${MARIADB_ROOT_PASSWORD} -e "CREATE DATABASE rplace;";
    mysql -u root --password=${MARIADB_ROOT_PASSWORD} -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';";
    mysql -u root --password=${MARIADB_ROOT_PASSWORD} -e "FLUSH PRIVILEGES";
    if [[ $ordinal -eq `expr $MAX_REPLICAS - 1` ]]; then
      new_ordinal=0;
    elif [[ $ordinal > `expr $MAX_REPLICAS - 1` ]]; then
      new_ordinal=`expr ${ordinal} - 1`;
    else
      new_ordinal=`expr ${ordinal} + 1`;
    fi
    mysql -u root --password=${MARIADB_ROOT_PASSWORD} -e "CHANGE MASTER TO
    MASTER_HOST='mariadb-${new_ordinal}.mariadb',
    MASTER_USER='${MARIADB_REPL_USER}${new_ordinal}',
    MASTER_PASSWORD='${MARIADB_REPL_PASSWORD}',
    MASTER_PORT=3306,
    MASTER_CONNECT_RETRY=10;";
    mysql -u root --password=${MARIADB_ROOT_PASSWORD} -e "START SLAVE;";
