apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: rplace
type: Opaque
stringData:
  mariadb-repl-username: {{ .Values.mariadb.REPL_USER }}
  mariadb-repl-password: {{ .Values.mariadb.REPL_PASSWORD }}
  mariadb-root-password: {{ .Values.mariadb.PASSWORD }}