apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: rplace
spec:
  serviceName: "mariadb"
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      # topologySpreadConstraints:
      #   - maxSkew: 1
      #     topologyKey: kubernetes.io/hostname
      #     whenUnsatisfiable: DoNotSchedule
      #     labelSelector:
      #       matchLabels:
      #         app: mariadb
      initContainers:
      - name: init-mariadb
        image: mariadb:10.7.4-focal
        imagePullPolicy: IfNotPresent
        command:
        - bash
        - "-c"
        - |
          set -ex
          # Copy config map to directory that already exists (but must be used as a volume for main container)
          ls /mnt/config-map
          [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
          ordinal=${BASH_REMATCH[1]}
          cp /mnt/config-map/mariadb.cnf /etc/mysql/conf.d/server-id.cnf
          cp /mnt/config-map/mariadb.sh /docker-entrypoint-initdb.d/init.sh
          echo server_id=300$ordinal >> /docker-entrypoint-initdb.d/init.sh
          # Add an offset to avoid reserved server-id=0 value.
          echo server-id=$((3000 + $ordinal)) >> /etc/mysql/conf.d/server-id.cnf
          cp /mnt/config-map/mariadb.cnf /etc/mysql/conf.d
          # Execute the script if needed (maybe for galera)
          # ./mnt/config-map/init.sh
          ls /etc/mysql/conf.d/
          cat /etc/mysql/conf.d/server-id.cnf
        volumeMounts:
          - name: mariadb-config
            mountPath: /mnt/config-map
          - name: confdir
            mountPath: /etc/mysql/conf.d # directory will be cleaned at the beginning
          - name: mariadb-init
            mountPath: /docker-entrypoint-initdb.d
      restartPolicy: Always
      containers:
      - name: mariadb
        image: mariadb:10.7.4-focal
        ports:
        - containerPort: 3306
          name: mariadb
        env:
        # Using Secrets
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-root-password
        - name: MARIADB_REPL_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-repl-username
        - name: MARIADB_REPL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-repl-password
        - name: MAX_REPLICAS
          value: "2"
        - name: MYSQL_INITDB_SKIP_TZINFO
          value: "yes"
        # Mount volumes from persistent volume claim
        volumeMounts:
        - name: mariadb-config
          mountPath: /mnt/config-map
        - name: datadir
          mountPath: /var/lib/mysql/
        - name: confdir
          mountPath: /etc/mysql/conf.d # directory will be cleaned at the beginning
        - name: mariadb-init
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mariadb-config
        configMap:
          name: mariadb-configmap
          defaultMode: 0544
      - name: confdir
        emptyDir: {}
      - name: mariadb-init
        emptyDir: {}

  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-ssd"
      resources:
        requests:
          storage: {{ .Values.mariadb.CAPACITY }}