# Default values for the rplace chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

backend:
  AT_SECRET: AT_SECRET
  RT_SECRET: RT_SECRET
  SESSION_TIME: 12h
  ROLE_ADMIN: inp.ddassieu
  LOCAL_PSCOPES: loc
  GLOBAL_PSCOPES: inp,insa
  CONTACT_TEAM: "{Damien Dassieu}-{https://m.me/Dami1Da}"
  imageVersion: v1.7

frontend:
  VITE_APP_BACKEND_URL: https://place.inpt.fr
  VITE_APP_BACKEND_API_URL: https://place.inpt.fr/api/v1
  VITE_APP_PSCOPES: inp,loc
  imageVersion: v1.6

admin:
  imageVersion: v1.0

redis:
  # HOST: redis://rplace:<redis_password>@redis:6379
  PASSWORD: <redis_password>
  CAPACITY: 8Gi   # 8Gi

mariadb:
  HOST: mariadb
  PORT: 3306
  USER: root
  PASSWORD: <maria_password>
  DATABASE: rplace
  DEV: false
  REPL_USER: repluser
  REPL_PASSWORD: <maria_replication_password>
  CAPACITY: 10Gi    # 20Gi

cronjob:
  rts:
    TIMER: 60    # push to redis every 5 seconds
  rtr:
    TIMER: 3     # push to mariadb every 60 seconds

