apiVersion: apps/v1
kind: Deployment
metadata:
  name: rplace-cronjob
  namespace: rplace
  labels:
    app: cronjob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cronjob
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: cronjob
    spec:
      containers:
        - name: rts
          image: harbor.k8s.inpt.fr/rplace/rts:v2
          imagePullPolicy: IfNotPresent
          env:
          - name: MARIADB_HOST
            value: "{{ .Values.mariadb.HOST }}"
          - name: MARIADB_PORT
            value: "{{ .Values.mariadb.PORT }}"
          - name: MARIADB_USER
            value: "{{ .Values.mariadb.USER }}"
          - name: MARIADB_PASSWORD
            value: "{{ .Values.mariadb.PASSWORD }}"
          - name: MARIADB_DATABASE
            value: "{{ .Values.mariadb.DATABASE }}"
          - name: MARIADB_DEV
            value: "{{ .Values.mariadb.DEV }}"
          - name: REDIS_HOST
            value: "{{ .Values.redis.HOST }}"
          - name: TIMER
            value: "{{ .Values.cronjob.rts.TIMER }}"
        - name: rtr
          image: harbor.k8s.inpt.fr/rplace/rtr:v2
          imagePullPolicy: IfNotPresent
          env:
          - name: REDIS_HOST
            value: {{ .Values.redis.HOST }}
          - name: TIMER
            value: "{{ .Values.cronjob.rtr.TIMER }}"