apiVersion: apps/v1
kind: Deployment
metadata:
  name: rplace-backend
  namespace: rplace
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: harbor.k8s.inpt.fr/rplace/backend:v1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: MARIADB_HOST
          value: "{{ .Values.mariadbHOST }}"
        - name: MARIADB_PORT
          value: "{{ .Values.mariadbPORT }}"
        - name: MARIADB_USER
          value: "{{ .Values.mariadbUSER }}"
        - name: MARIADB_PASSWORD
          value: "{{ .Values.mariadb.PASSWORD }}"
        - name: MARIADB_DATABASE
          value: "{{ .Values.mariadbDATABASE }}"
        - name: MARIADB_DEV
          value: "{{ .Values.mariadbDEV }}"
        - name: REDIS_HOST
          value: "{{ .Values.redis.HOST }}"
        - name: AT_SECRET
          value: "{{ .Values.backend.AT_SECRET }}"
        - name: RT_SECRET
          value: "{{ .Values.backend.RT_SECRET }}"
        - name: ROLE_ADMIN
          value: "{{ .Values.backend.ROLE_ADMIN }}"
        - name: LOCAL_PSCOPE
          value: "{{ .Values.backend.LOCAL_PSCOPE }}"
      imagePullSecrets:
      - name: rplace-pull-secret
