apiVersion: apps/v1
kind: Deployment
metadata:
  name: rplace-backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: harbor.k8s.inpt.fr/rplace/backend:v1.7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: MARIADB_HOST
          value: "{{ .Values.mariadb.HOST }}"
        - name: MARIADB_PORT
          value: "{{ .Values.mariadb.PORT }}"
        - name: MARIADB_USER
          value: "{{ .Values.mariadb.USER }}"
        - name: MARIADB_PASSWORD
          value: "{{ .Values.mariadb.PASSWORD }}"
        - name: MARIADB_DATABASE
          value: "{{ .Values.mariadb.DATABASE }}"
        - name: MARIADB_DEV
          value: "{{ .Values.mariadb.DEV }}"
        - name: REDIS_HOST
          value: "redis://rplace:{{ .Values.redis.PASSWORD }}@redis:6379"
        - name: AT_SECRET
          value: "{{ .Values.backend.AT_SECRET }}"
        - name: RT_SECRET
          value: "{{ .Values.backend.RT_SECRET }}"
        - name: ROLE_ADMIN
          value: "{{ .Values.backend.ROLE_ADMIN }}"
        - name: LOCAL_PSCOPES
          value: "{{ .Values.backend.LOCAL_PSCOPES }}"
        - name: GLOBAL_PSCOPES
          value: "{{ .Values.backend.GLOBAL_PSCOPES }}"
        - name: CONTACT_TEAM
          value: "{{ .Values.backend.CONTACT_TEAM }}"
        - name: SESSION_TIME
          value: "{{ .Values.backend.SESSION_TIME }}"
      imagePullSecrets:
      - name: rplace-pull-secret
