apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-backend
  namespace: rplace
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: rplace.inpt.fr
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: rplace-backend
            port:
              number: 8080