apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-configmap
  namespace: rplace
data:
  mariadb.cnf: |
    [mariadb]
    #plugin_load_add=simple_password_check
    #plugin_load_add=password_reuse_check       # this is alpha maturity
    #plugin_maturity=alpha
    #simple_password_check_minimal_length=5     # default 8
    #simple_password_check_digits=0             # default 1
    #simple_password_check_letters_same_case=0  # default 1
    #simple_password_check_other_characters=0   # default 1
    #strict_password_validation=1              # if set to 1 hash passwords are used
  init.sh: |
    set -ex
    # Generate mysql server-id from pod ordinal index.
    echo "Hi from script"
    [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
    ordinal=${BASH_REMATCH[1]}
    echo [mariadb] > /etc/mysql/conf.d/server-id.cnf
    # Add an offset to avoid reserved server-id=0 value.
    echo server-id=$((100 + $ordinal)) >> etc/mysql/server-id.cnf
  master.cnf: |
    [mariadb]
    log-bin                         # enable binary loging
    server_id=3000                  # used to uniquely identify the server
    #log-basename=my-mariadb         # used to be independent of to hostname changes (otherwise is in datadir/mysql)
    #binlog-format=MIXED            #default
  replica.cnf: |
    [mariadb]
    read-only=1
    server_id=3001                  # used to uniquely identify the server
    #log-basename=my-mariadb         # used to be independent of to hostname changes (otherwise is in datadir/mysql)
    #binlog-format=MIXED            #default
  master.sh: |
    mysql -u root --password=${MARIADB_ROOT_PASSWORD} -e "CREATE USER '${MARIADB_REPL_USER}'@'%' IDENTIFIED BY '${MARIADB_REPL_PASSWORD}';";
    mysql -u root --password=${MARIADB_ROOT_PASSWORD} -e "GRANT REPLICATION SLAVE ON *.* TO '${MARIADB_REPL_USER}'@'%';";
    mysql -u root --password=${MARIADB_ROOT_PASSWORD} -e "CREATE DATABASE rplace;";
  replica.sh: |
    mysql -u root --password=${MARIADB_ROOT_PASSWORD} -e "CHANGE MASTER TO
    MASTER_HOST='mariadb-0.mariadb',
    MASTER_USER='${MARIADB_REPL_USER}',
    MASTER_PASSWORD='${MARIADB_REPL_PASSWORD}',
    MASTER_PORT=3306,
    MASTER_CONNECT_RETRY=10;";
    mysql -u root --password=${MARIADB_ROOT_PASSWORD} -e "START SLAVE;";
    mysql -u root --password=${MARIADB_ROOT_PASSWORD} -e "SHOW SLAVE STATUS;";