apiVersion: mariadb.mmontes.io/v1alpha1
kind: MaxScale
metadata:
  name: maxscale
spec:
  image: mariadb/maxscale:23.08
  imagePullPolicy: IfNotPresent

  replicas: 3

  servers:
    - name: mariadb-0
      address: mariadb-repl-0.mariadb-repl-internal.default.svc.cluster.local
      port: 3306
      protocol: MariaDBBackend
      maintenance: false
      params:
        max_routing_connections: "2048"
    - name: mariadb-1
      address: mariadb-repl-1.mariadb-repl-internal.default.svc.cluster.local
    - name: mariadb-2
      address: mariadb-repl-2.mariadb-repl-internal.default.svc.cluster.local

  services:
    - name: rw-router
      router: readwritesplit
      params:
        transaction_replay: "true"
        transaction_replay_attempts: "10"
        transaction_replay_timeout: "5s"
        max_slave_connections: "255"
        max_replication_lag: "3s"
        master_accept_reads: "true"
      listener:
        name: rw-listener
        port: 3306
        protocol: MariaDBProtocol
        params: 
          connection_metadata: "tx_isolation=auto"
        suspend: false
      suspend: false
    - name: rconn-master-router
      router: readconnroute
      params:
        router_options: "master"
        max_replication_lag: "3s"
        master_accept_reads: "true"
      listener:
        port: 3307
    - name: rconn-slave-router
      router: readconnroute
      params:
        router_options: "slave"
        max_replication_lag: "3s"
      listener:
        port: 3308

  monitor:
    name: mariadb-monitor
    module: mariadbmon
    interval: 2s
    cooperativeMonitoring: majority_of_all
    params:
      auto_failover: "true"
      auto_rejoin: "true"
      switchover_on_low_disk_space: "true"
    suspend: false

  admin:
    port: 8989
    guiEnabled: true

  config:
    params:
      log_info: "true"
    volumeClaimTemplate:
      resources:
        requests:
          storage: {{ .Values.mariadb.CAPACITY }}
      accessModes:
        - ReadWriteOnce
    sync:
      database: rplace
      interval: 5s
      timeout: 10s

  auth:
    generate: true
    adminUsername: mariadb-operator
    adminPasswordSecretKeyRef:
      name: mariadb-maxscale
      key: password
    deleteDefaultAdmin: true
    clientUsername: maxscale-client
    clientPasswordSecretKeyRef:
      name: mariadb-maxscale
      key: password
    serverUsername: maxscale-server
    serverPasswordSecretKeyRef:
      name: mariadb-maxscale
      key: password
    monitorUsername: maxscale-monitor
    monitorPasswordSecretKeyRef:
      name: mariadb-maxscale
      key: password
    syncUsername: maxscale-sync
    syncPasswordSecretKeyRef:
      name: mariadb-maxscale
      key: password

  podSecurityContext:
    runAsUser: 0

  securityContext:
    allowPrivilegeEscalation: false

  updateStrategy:
    type: RollingUpdate

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 1Gi

  podDisruptionBudget:
    maxUnavailable: 66%