apiVersion: apps/v1
kind: Deployment
metadata:
  name: rplace-admin
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: harbor.k8s.inpt.fr/rplace/admin:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: PUBLIC_URL_API
          value: "{{ .Values.admin.PUBLIC_URL_API }}"
        - name: ORIGIN
          value: "{{ .Values.admin.ORIGIN }}"
        - name: PORT
          value: "5173"
      imagePullSecrets:
      - name: rplace-pull-secret
