apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modify-pods
  namespace: pixel-war
rules:
  - apiGroups: ["", "discovery.k8s.io", "apps"]
    resources:
      - pods
      - statefulsets
      - endpointslices
    verbs:
      - get
      - list
      - delete
      - update
      - patch