apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  namespace: pixel-war
  labels:
    app: redis
spec:
  clusterIP: None
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  type: ClusterIP
