apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sentinel
  namespace: rplace
spec:
  serviceName: sentinel
  replicas: 1
  selector:
    matchLabels:
      app: sentinel
  template:
    metadata:
      labels:
        app: sentinel
    spec:
      serviceAccountName: internal-kubectl
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - sentinel
            topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: config
        image: redis:6.2.3
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-password
        command: [ "bash", "-c" ]
        args:
          - |
            # Install curl
            apt-get update -y
            apt-get upgrade -y
            apt-get install curl -y

            # Install kubectl binary
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mv ./kubectl /usr/local/bin/kubectl

            echo $(kubectl get endpointslices -n rplace | grep redis-sentinel)
            edpts="<none>"
            while [[ $edpts == *"<none>"* ]];
            do
                edpts=$(kubectl get endpointslices -n rplace | grep redis-sentinel)
            done

            arrIN=(${edpts//,/ })
            for i in "${arrIN[@]}"; do
                address=(${i//:/ })
                nodes+=(${address[0]})
            done
            nodes=("${nodes[@]:3}")
            unset 'nodes[${#nodes[@]}-1]'

            echo $nodes
            #nodes=redis-0.redis-sentinel,redis-1.redis-sentinel,redis-2.redis-sentinel

            MASTER=
            while [ "$MASTER" == "" ];
            do
                #for i in ${nodes//,/ }
                for i in "${nodes[@]}"
                do
                    echo "finding master at $i"
                    MASTER=$(redis-cli --no-auth-warning --raw -h $i -a $REDIS_PASSWORD info replication | awk '{print $1}' | grep role: | cut -d ":" -f2)
                    if [[ "$MASTER" == *"master"* ]]; then
                        echo "found $i"
                        MASTER=$i
                        break
                    else
                        echo "no master found"
                        MASTER=
                    fi
                done
            done

            echo "sentinel monitor mymaster $MASTER 6379 2" >> /tmp/master
            echo "port 5000
            sentinel resolve-hostnames yes
            sentinel announce-hostnames yes
            $(cat /tmp/master)
            sentinel down-after-milliseconds mymaster 5000
            sentinel failover-timeout mymaster 60000
            sentinel parallel-syncs mymaster 1
            sentinel auth-pass mymaster $REDIS_PASSWORD
            " > /etc/redis/sentinel.conf

            # Set password in the config file
            sed -i "s/VERY_SECRET_PASSWORD/$REDIS_PASSWORD/" /etc/redis/sentinel.conf
            cat /etc/redis/sentinel.conf
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis/
      containers:
      - name: sentinel
        image: redis/redis-stack-server:latest
        command: ["redis-sentinel"]
        args: ["/etc/redis/sentinel.conf"]
        ports:
        - containerPort: 5000
          name: sentinel
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis/
        - name: data
          mountPath: /data
      volumes:
      - name: redis-config
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-ssd"
      resources:
        requests:
          storage: 50Mi
